=== uo300652/sew/xml/circuito.dtd
<!ELEMENT circuito (nombre, longitud, anchuraMedia, fecha, horaInicio, numeroVueltas, localidadProxima, pais, patrocinador, referencias, fotografias, videos, puntoOrigen, tramos, vencedor, tiempoVencedor, clasificados)>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT longitud (#PCDATA)>
<!ATTLIST longitud cantidad CDATA #REQUIRED>
<!ATTLIST longitud unidad CDATA #REQUIRED>
<!ELEMENT anchuraMedia (#PCDATA)>
<!ATTLIST anchuraMedia cantidad CDATA #REQUIRED>
<!ATTLIST anchuraMedia unidad CDATA #REQUIRED>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT horaInicio (#PCDATA)>
<!ELEMENT numeroVueltas (#PCDATA)>
<!ELEMENT localidadProxima (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT patrocinador (#PCDATA)>
<!ELEMENT referencias (referencia+)>
<!ELEMENT referencia  (#PCDATA)>
<!ATTLIST referencia fuente CDATA #REQUIRED>
<!ATTLIST referencia enlace CDATA #REQUIRED>
<!ELEMENT fotografias  (fotografia+)>
<!ELEMENT fotografia  EMPTY>
<!ATTLIST fotografia 
    url CDATA #REQUIRED
    descripcion CDATA #IMPLIED>
<!ELEMENT videos  (video+)>
<!ELEMENT video  EMPTY>
<!ATTLIST video 
    url CDATA #REQUIRED
    descripcion CDATA #IMPLIED>
<!ELEMENT puntoOrigen (longitudPunto, latitud, altitud)>
<!ELEMENT tramos (tramo+)>
<!ELEMENT tramo (punto, distancia, sector)>
<!ELEMENT punto (longitudPunto, latitud, altitud)>
<!ELEMENT longitudPunto (#PCDATA)>
<!ATTLIST longitudPunto cantidad CDATA #REQUIRED>
<!ATTLIST longitudPunto unidad CDATA #REQUIRED>
<!ELEMENT latitud (#PCDATA)>
<!ATTLIST latitud cantidad CDATA #REQUIRED>
<!ATTLIST latitud unidad CDATA #REQUIRED>
<!ELEMENT altitud (#PCDATA)>
<!ATTLIST altitud cantidad CDATA #REQUIRED>
<!ATTLIST altitud unidad CDATA #REQUIRED>
<!ELEMENT distancia (#PCDATA)>
<!ATTLIST distancia cantidad CDATA #REQUIRED>
<!ATTLIST distancia unidad CDATA #REQUIRED>
<!ELEMENT sector (#PCDATA)>
<!ELEMENT vencedor (#PCDATA)>
<!ELEMENT tiempoVencedor (#PCDATA)>
<!ELEMENT clasificados (clasificado+)>
<!ELEMENT clasificado (#PCDATA)>

=== uo300652/sew/xml/circuito.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE circuito SYSTEM "circuito.dtd">
<circuito>
    <nombre>Chang International Circuit</nombre>
    <longitud cantidad="4553" unidad="metros"></longitud>
    <anchuraMedia cantidad="12" unidad="metros"></anchuraMedia>
    <fecha>2025-03-02</fecha>
    <horaInicio>09:00:00+01:00</horaInicio>
    <numeroVueltas>26</numeroVueltas>
    <localidadProxima>Buriram</localidadProxima>
    <pais>Tailandia</pais>
    <patrocinador>PTT</patrocinador>

    <referencias>
        <referencia fuente="Wikipedia" enlace="https://es.wikipedia.org/wiki/Circuito_Internacional_de_Chang">
            Ofrece información detallada sobre el circuito, incluyendo su ubicación, características y eventos importantes.
        </referencia>
        <referencia fuente="Vetkuro" enlace="https://vetkuro.com/tracks/buriram">
            Presenta una descripción del circuito, su infraestructura y su historia en el ámbito del automovilismo.
        </referencia>
        <referencia fuente="Motorsport Guides" enlace="https://motorsportguides.com/chang-international-circuit/">
            El Chang International Circuit es un moderno circuito de carreras situado en Buriram, Tailandia. Inaugurado en 2014, es el primer circuito en Tailandia con certificación FIA Grado 1 y FIM Grado A.
        </referencia>
    </referencias>

    <fotografias>
        <fotografia url="./multimedia/LineaDeMeta.jpg" descripcion="Fotografia de la linea de meta"/>
         <fotografia url="./multimedia/LineaDeMetaCarrera.jpg" descripcion="Fotografia de la linea de meta mientras que trascurre una carrera"/>
          <fotografia url="./multimedia/Panorama.jpg" descripcion="Fotografia de la vista general del Chang International Circuit" />
    </fotografias>

    <videos>
        <video url="./multimedia/ChangInternationalCircuit_video.mp4" descripcion="Video de una moto corriendo anunciando la carrera en el Chang International Circuit" />
    </videos>

    <puntoOrigen>
        <longitudPunto cantidad="103.084631" unidad="grados"></longitudPunto>
        <latitud cantidad="14.958563" unidad="grados"></latitud>
        <altitud cantidad="179.77" unidad="metros"></altitud>
    </puntoOrigen>

    <tramos>
        <tramo>
            <punto>
                <longitudPunto cantidad="103.082364" unidad="grados"></longitudPunto>
                <latitud cantidad="14.959569" unidad="grados"></latitud>
                <altitud cantidad="179.83" unidad="metros"></altitud>
            </punto>
            <distancia cantidad="269.32" unidad="metros"></distancia>
            <sector>1</sector>
        </tramo>
        <tramo>
            <punto>
                <longitudPunto cantidad="103.082253" unidad="grados"></longitudPunto>
                <latitud cantidad="14.959689" unidad="grados"></latitud>
                <altitud cantidad="179.18" unidad="metros"></altitud>
            </punto>
            <distancia cantidad="17.75" unidad="metros"></distancia>
            <sector>1</sector>
        </tramo>
        <tramo>
            <punto>
                <longitudPunto cantidad="103.082245" unidad="grados"></longitudPunto>
                <latitud cantidad="14.959844" unidad="grados"></latitud>
                <altitud cantidad="179.24" unidad="metros"></altitud>
            </punto>
            <distancia cantidad="17.55" unidad="metros"></distancia>
            <sector>1</sector>
        </tramo>
        <tramo>
            <punto>
                <longitudPunto cantidad="103.083470" unidad="grados"></longitudPunto>
                <latitud cantidad="14.964903" unidad="grados"></latitud>
                <altitud cantidad="173" unidad="metros"></altitud>
            </punto>
            <distancia cantidad="565.27" unidad="metros"></distancia>
            <sector>1</sector>
        </tramo>
        <tramo>
            <punto>
                <longitudPunto cantidad="103.083952" unidad="grados"></longitudPunto>
                <latitud cantidad="14.968485" unidad="grados"></latitud>
                <altitud cantidad="168.9" unidad="metros"></altitud>
            </punto>
            <distancia cantidad="400.32" unidad="metros"></distancia>
            <sector>1</sector>
        </tramo>
        <tramo>
            <punto>
                <longitudPunto cantidad="103.084205" unidad="grados"></longitudPunto>
                <latitud cantidad="14.968694" unidad="grados"></latitud>
                <altitud cantidad="166.29" unidad="metros"></altitud>
            </punto>
            <distancia cantidad="35.24" unidad="metros"></distancia>
            <sector>1</sector>
        </tramo>
        <tramo>
            <punto>
                <longitudPunto cantidad="103.084450" unidad="grados"></longitudPunto>
                <latitud cantidad="14.968688" unidad="grados"></latitud>
                <altitud cantidad="165.43" unidad="metros"></altitud>
            </punto>
            <distancia cantidad="27" unidad="metros"></distancia>
            <sector>1</sector>
        </tramo>
        <tramo>
            <punto>
                <longitudPunto cantidad="103.084660" unidad="grados"></longitudPunto>
                <latitud cantidad="14.968542" unidad="grados"></latitud>
                <altitud cantidad="164.62" unidad="metros"></altitud>
            </punto>
            <distancia cantidad="27.86" unidad="metros"></distancia>
            <sector>1</sector>
        </tramo>
        <tramo>
            <punto>
                <longitudPunto cantidad="103.084777" unidad="grados"></longitudPunto>
                <latitud cantidad="14.968329" unidad="grados"></latitud>
                <altitud cantidad="165.06" unidad="metros"></altitud>
            </punto>
            <distancia cantidad="27.38" unidad="metros"></distancia>
            <sector>1</sector>
        </tramo>
        <tramo>
            <punto>
                <longitudPunto cantidad="103.083702" unidad="grados"></longitudPunto>
                <latitud cantidad="14.961267" unidad="grados"></latitud>
                <altitud cantidad="177.95" unidad="metros"></altitud>
            </punto>
            <distancia cantidad="778.27" unidad="metros"></distancia>
            <sector>1</sector>
        </tramo>
        <tramo>
            <punto>
                <longitudPunto cantidad="103.083697" unidad="grados"></longitudPunto>
                <latitud cantidad="14.960910" unidad="grados"></latitud>
                <altitud cantidad="177.95" unidad="metros"></altitud>
            </punto>
            <distancia cantidad="40.5" unidad="metros"></distancia>
            <sector>2</sector>
        </tramo>
        <tramo>
            <punto>
                <longitudPunto cantidad="103.083861" unidad="grados"></longitudPunto>
                <latitud cantidad="14.960550" unidad="grados"></latitud>
                <altitud cantidad="170.99" unidad="metros"></altitud>
            </punto>
            <distancia cantidad="45.6" unidad="metros"></distancia>
            <sector>2</sector>
        </tramo>
        <tramo>
            <punto>
                <longitudPunto cantidad="103.085444" unidad="grados"></longitudPunto>
                <latitud cantidad="14.959002" unidad="grados"></latitud>
                <altitud cantidad="176.35" unidad="metros"></altitud>
            </punto>
            <distancia cantidad="242.56" unidad="metros"></distancia>
            <sector>2</sector>
        </tramo>
        <tramo>
            <punto>
                <longitudPunto cantidad="103.085630" unidad="grados"></longitudPunto>
                <latitud cantidad="14.958910" unidad="grados"></latitud>
                <altitud cantidad="177.3" unidad="metros"></altitud>
            </punto>
            <distancia cantidad="22.2" unidad="metros"></distancia>
            <sector>2</sector>
        </tramo>
        <tramo>
            <punto>
                <longitudPunto cantidad="103.085837" unidad="grados"></longitudPunto>
                <latitud cantidad="14.958974" unidad="grados"></latitud>
                <altitud cantidad="177.85" unidad="metros"></altitud>
            </punto>
            <distancia cantidad="23.16" unidad="metros"></distancia>
            <sector>2</sector>
        </tramo>
        <tramo>
            <punto>
                <longitudPunto cantidad="103.085978" unidad="grados"></longitudPunto>
                <latitud cantidad="14.959150" unidad="grados"></latitud>
                <altitud cantidad="178.12" unidad="metros"></altitud>
            </punto>
            <distancia cantidad="24.38" unidad="metros"></distancia>
            <sector>2</sector>
        </tramo>
        <tramo>
            <punto>
                <longitudPunto cantidad="103.086215" unidad="grados"></longitudPunto>
                <latitud cantidad="14.959705" unidad="grados"></latitud>
                <altitud cantidad="180.81" unidad="metros"></altitud>
            </punto>
            <distancia cantidad="66.53" unidad="metros"></distancia>
            <sector>2</sector>
        </tramo>
        <tramo>
            <punto>
                <longitudPunto cantidad="103.086222" unidad="grados"></longitudPunto>
                <latitud cantidad="14.959958" unidad="grados"></latitud>
                <altitud cantidad="182.81" unidad="metros"></altitud>
            </punto>
            <distancia cantidad="28.06" unidad="metros"></distancia>
            <sector>2</sector>
        </tramo>
        <tramo>
            <punto>
                <longitudPunto cantidad="103.086133" unidad="grados"></longitudPunto>
                <latitud cantidad="14.960195" unidad="grados"></latitud>
                <altitud cantidad="180.35" unidad="metros"></altitud>
            </punto>
