=== uo300652/sew/xml/circuito.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.uniovi.es"
	xmlns="http://www.uniovi.es"
	elementFormDefault="qualified">

	<xs:element name="circuito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="longitud" />
				<xs:element ref="anchuraMedia" />
				<xs:element ref="fecha" />
				<xs:element ref="horaInicio" />
				<xs:element ref="numeroVueltas" />
				<xs:element ref="localidadProxima" />
				<xs:element ref="pais" />
				<xs:element ref="patrocinador" />
				<xs:element ref="referencias" />
				<xs:element ref="fotografias" />
				<xs:element ref="videos" />
				<xs:element ref="puntoOrigen" />
				<xs:element ref="tramos" />
				<xs:element ref="vencedor" />
				<xs:element ref="tiempoVencedor" />
				<xs:element ref="clasificados" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nombre" type="xs:string" />
	<xs:element name="longitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="cantidad" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:decimal">
								<xs:minInclusive value="0"/>
								<xs:maxInclusive value="10000"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="anchuraMedia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="cantidad" type="xs:decimal" use="required" />
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="fecha" type="xs:date" />
	<xs:element name="horaInicio" type="xs:time" />
	<xs:element name="numeroVueltas">
		<xs:simpleType>
			<xs:restriction base="xs:positiveInteger">
				<xs:minInclusive value="15"/>
				<xs:maxInclusive value="35"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="localidadProxima" type="xs:string" />
	<xs:element name="pais" type="xs:string" />
	<xs:element name="patrocinador" type="xs:string" />
	<xs:element name="referencias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="referencia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="referencia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="fuente" type="xs:string" use="required" />
					<xs:attribute name="enlace" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="fotografias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="5" ref="fotografia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="fotografia">
		<xs:complexType>
			<xs:attribute name="url" type="xs:string" use="required" />
			<xs:attribute name="descripcion" type="xs:string" />
		</xs:complexType>
	</xs:element>
	<xs:element name="videos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="3" ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="video">
		<xs:complexType>
			<xs:attribute name="url" type="xs:string" use="required" />
			<xs:attribute name="descripcion" type="xs:string" />
		</xs:complexType>
	</xs:element>
	<xs:element name="puntoOrigen">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitudPunto" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="tramos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="tramo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="tramo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="punto" />
				<xs:element ref="distancia" />
				<xs:element ref="sector" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="punto">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitudPunto" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="longitudPunto">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="cantidad" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:decimal">
								<xs:minInclusive value="-180"/>
								<xs:maxInclusive value="180"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="latitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="cantidad" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:decimal">
								<xs:minInclusive value="-90"/>
								<xs:maxInclusive value="90"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="unidad" type="xs:string" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="altitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="cantidad" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:decimal">
								<xs:minInclusive value="0"/>
								<xs:maxInclusive value="5000"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="distancia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="cantidad" type="xs:decimal" use="required" />
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="sector" type="xs:integer" />
	<xs:element name="vencedor" type="xs:string" />
	<xs:element name="tiempoVencedor" type="xs:duration" />
	<xs:element name="clasificados">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="3" ref="clasificado" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="clasificado" type="xs:string" />
</xs:schema>

=== uo300652/sew/xml/circuitoEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<circuito
xmlns="http://www.uniovi.es"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.uniovi.es circuito.xsd"
>
    <nombre>Chang International Circuit</nombre>
    <longitud cantidad="4553" unidad="metros"></longitud>
    <anchuraMedia cantidad="12" unidad="metros"></anchuraMedia>
    <fecha>2025-03-02</fecha>
    <horaInicio>09:00:00+01:00</horaInicio>
    <numeroVueltas>26</numeroVueltas>
    <localidadProxima>Buriram</localidadProxima>
    <pais>Tailandia</pais>
    <patrocinador>PTT</patrocinador>

    <referencias>
        <referencia fuente="Wikipedia" enlace="https://es.wikipedia.org/wiki/Circuito_Internacional_de_Chang">
            Ofrece información detallada sobre el circuito, incluyendo su ubicación, características y eventos importantes.
        </referencia>
        <referencia fuente="Vetkuro" enlace="https://vetkuro.com/tracks/buriram">
            Presenta una descripción del circuito, su infraestructura y su historia en el ámbito del automovilismo.
        </referencia>
        <referencia fuente="Motorsport Guides" enlace="https://motorsportguides.com/chang-international-circuit/">
            El Chang International Circuit es un moderno circuito de carreras situado en Buriram, Tailandia. Inaugurado en 2014, es el primer circuito en Tailandia con certificación FIA Grado 1 y FIM Grado A.
        </referencia>
    </referencias>

    <fotografias>
        <fotografia url="./multimedia/LineaDeMeta.jpg" descripcion="Fotografia de la linea de meta"/>
         <fotografia url="./multimedia/LineaDeMetaCarrera.jpg" descripcion="Fotografia de la linea de meta mientras que trascurre una carrera"/>
          <fotografia url="./multimedia/Panorama.jpg" descripcion="Fotografia de la vista general del Chang International Circuit" />
    </fotografias>

    <videos>
        <video url="./multimedia/ChangInternationalCircuit_video.mp4" descripcion="Video de una moto corriendo anunciando la carrera en el Chang International Circuit" />
    </videos>

    <puntoOrigen>
        <longitudPunto cantidad="103.084631" unidad="grados"></longitudPunto>
        <latitud cantidad="14.958563" unidad="grados"></latitud>
        <altitud cantidad="179.77" unidad="metros"></altitud>
    </puntoOrigen>

    <tramos>
        <tramo>
            <punto>
                <longitudPunto cantidad="103.082364" unidad="grados"></longitudPunto>
                <latitud cantidad="14.959569" unidad="grados"></latitud>
                <altitud cantidad="179.83" unidad="metros"></altitud>
            </punto>
            <distancia cantidad="269.32" unidad="metros"></distancia>
            <sector>1</sector>
        </tramo>
        <tramo>
            <punto>
                <longitudPunto cantidad="103.082253" unidad="grados"></longitudPunto>
                <latitud cantidad="14.959689" unidad="grados"></latitud>
                <altitud cantidad="179.18" unidad="metros"></altitud>
            </punto>
            <distancia cantidad="17.75" unidad="metros"></distancia>
            <sector>1</sector>
        </tramo>
        <tramo>
            <punto>
                <longitudPunto cantidad="103.082245" unidad="grados"></longitudPunto>
                <latitud cantidad="14.959844" unidad="grados"></latitud>
                <altitud cantidad="179.24" unidad="metros"></altitud>
            </punto>
            <distancia cantidad="17.55" unidad="metros"></distancia>
            <sector>1</sector>
        </tramo>
        <tramo>
            <punto>
                <longitudPunto cantidad="103.083470" unidad="grados"></longitudPunto>
                <latitud cantidad="14.964903" unidad="grados"></latitud>
                <altitud cantidad="173" unidad="metros"></altitud>
            </punto>
            <distancia cantidad="565.27" unidad="metros"></distancia>
            <sector>1</sector>
        </tramo>
        <tramo>
            <punto>
                <longitudPunto cantidad="103.083952" unidad="grados"></longitudPunto>
                <latitud cantidad="14.968485" unidad="grados"></latitud>
                <altitud cantidad="168.9" unidad="metros"></altitud>
            </punto>
            <distancia cantidad="400.32" unidad="metros"></distancia>
            <sector>1</sector>
        </tramo>
        <tramo>
            <punto>
                <longitudPunto cantidad="103.084205" unidad="grados"></longitudPunto>
                <latitud cantidad="14.968694" unidad="grados"></latitud>
                <altitud cantidad="166.29" unidad="metros"></altitud>
            </punto>
            <distancia cantidad="35.24" unidad="metros"></distancia>
            <sector>1</sector>
        </tramo>
        <tramo>
            <punto>
                <longitudPunto cantidad="103.084450" unidad="grados"></longitudPunto>
                <latitud cantidad="14.968688" unidad="grados"></latitud>
                <altitud cantidad="165.43" unidad="metros"></altitud>
            </punto>
            <distancia cantidad="27" unidad="metros"></distancia>
            <sector>1</sector>
        </tramo>
        <tramo>
            <punto>
                <longitudPunto cantidad="103.084660" unidad="grados"></longitudPunto>
                <latitud cantidad="14.968542" unidad="grados"></latitud>
                <altitud cantidad="164.62" unidad="metros"></altitud>
            </punto>
            <distancia cantidad="27.86" unidad="metros"></distancia>
            <sector>1</sector>
        </tramo>
        <tramo>
            <punto>
                <longitudPunto cantidad="103.084777" unidad="grados"></longitudPunto>
                <latitud cantidad="14.968329" unidad="grados"></latitud>
                <altitud cantidad="165.06" unidad="metros"></altitud>
            </punto>
            <distancia cantidad="27.38" unidad="metros"></distancia>
            <sector>1</sector>
        </tramo>
        <tramo>
            <punto>
                <longitudPunto cantidad="103.083702" unidad="grados"></longitudPunto>
                <latitud cantidad="14.961267" unidad="grados"></latitud>
                <altitud cantidad="177.95" unidad="metros"></altitud>
            </punto>
            <distancia cantidad="778.27" unidad="metros"></distancia>
            <sector>1</sector>
        </tramo>
        <tramo>
            <punto>
                <longitudPunto cantidad="103.083697" unidad="grados"></longitudPunto>
                <latitud cantidad="14.960910" unidad="grados"></latitud>
                <altitud cantidad="177.95" unidad="metros"></altitud>
            </punto>
            <distancia cantidad="40.5" unidad="metros"></distancia>
            <sector>2</sector>
        </tramo>
        <tramo>
            <punto>
                <longitudPunto cantidad="103.083861" unidad="grados"></longitudPunto>
                <latitud cantidad="14.960550" unidad="grados"></latitud>
                <altitud cantidad="170.99" unidad="metros"></altitud>
            </punto>
            <distancia cantidad="45.6" unidad="metros"></distancia>
            <sector>2</sector>
        </tramo>
        <tramo>
            <punto>
                <longitudPunto cantidad="103.085444" unidad="grados"></longitudPunto>
                <latitud cantidad="14.959002" unidad="grados"></latitud>
                <altitud cantidad="176.35" unidad="metros"></altitud>
            </punto>
            <distancia cantidad="242.56" unidad="metros"></distancia>
            <sector>2</sector>
        </tramo>
        <tramo>
            <punto>
                <longitudPunto cantidad="103.085630" unidad="grados"></longitudPunto>
                <latitud cantidad="14.958910" unidad="grados"></latitud>
                <altitud cantidad="177.3" unidad="metros"></altitud>
            </punto>
            <distancia cantidad="22.2" unidad="metros"></distancia>
            <sector>2</sector>
        </tramo>
        <tramo>
            <punto>
                <longitudPunto cantidad="103.085837" unidad="grados"></longitudPunto>
                <latitud cantidad="14.958974" unidad="grados"></latitud>
                <altitud cantidad="177.85" unidad="metros"></altitud>
            </punto>
            <distancia cantidad="23.16" unidad="metros"></distancia>
            <sector>2</sector>
        </tramo>
        <tramo>
            <punto>
                <longitudPunto cantidad="103.085978" unidad="grados"></longitudPunto>
                <latitud cantidad="14.959150" unidad="grados"></latitud>
                <altitud cantidad="178.12" unidad="metros"></altitud>
            </punto>
            <distancia cantidad="24.38" unidad="metros"></distancia>
            <sector>2</sector>
        </tramo>
        <tramo>
            <punto>
                <longitudPunto cantidad="103.086215" unidad="grados"></longitudPunto>
                <latitud cantidad="14.959705" unidad="grados"></latitud>
                <altitud cantidad="180.81" unidad="metros"></altitud>
            </punto>
            <distancia cantidad="66.53" unidad="metros"></distancia>
            <sector>2</sector>
        </tramo>
        <tramo>
            <punto>
                <longitudPunto cantidad="103.086222" unidad="grados"></longitudPunto>
                <latitud cantidad="14.959958" unidad="grados"></latitud>
                <altitud cantidad="182.81" unidad="metros"></altitud>
            </punto>
            <distancia cantidad="28.06" unidad="metros"></distancia>
            <sector>2</sector>
        </tramo>
        <tramo>
            <punto>
                <longitudPunto cantidad="103.086133" unidad="grados"></longitudPunto>
                <latitud cantidad="14.960195" unidad="grados"></latitud>
